services:
  web_api:
    container_name: web_api
    build: .
    env_file: .env
    command: uvicorn api.main:api_app --reload --port 80 --host 0.0.0.0
    ports:
      - "8080:80"
    depends_on:
      - rabbitmq
    volumes:
      - ./open_crawler:/app

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.2-management
    hostname: rabbitmq
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    container_name: redis
    image: redis
    hostname: redis
    env_file: .env
    ports:
      - "6379:6379"

  crawl_worker: &worker
    container_name: crawl_worker
    build: .
    env_file: .env
    command: watchfiles --filter python 'celery -A celery_broker.main.celery_app worker -l info -P solo -n crawl_worker -Q crawl_queue'
    depends_on:
      - rabbitmq
      - web_api
    volumes:
      - ./open_crawler:/app
      - tmp:/tmp

  accessibility_worker:
    <<: *worker
    container_name: accessibility_worker
    command: watchfiles --filter python 'celery -A celery_broker.main.celery_app worker -l info -P solo -n accessibility_worker -Q accessibility_queue'

  technologies_worker:
    <<: *worker
    container_name: technologies_worker
    command: watchfiles --filter python 'celery -A celery_broker.main.celery_app worker -l info -P solo -n technologies_worker -Q technologies_queue'

  good_practices_worker:
    <<: *worker
    container_name: good_practices_worker
    command: watchfiles --filter python 'celery -A celery_broker.main.celery_app worker -l info -P solo -n good_practices_worker -Q good_practices_queue'

  responsiveness_worker:
    <<: *worker
    container_name: responsiveness_worker
    command: watchfiles --filter python 'celery -A celery_broker.main.celery_app worker -l info -P solo -n responsiveness_worker -Q responsiveness_queue'

  carbon_footprint_worker:
    <<: *worker
    container_name: carbon_footprint_worker
    command: watchfiles --filter python 'celery -A celery_broker.main.celery_app worker -l info -P solo -n carbon_footprint_worker -Q carbon_footprint_queue'

  upload_worker:
    <<: *worker
    container_name: upload_worker
    command: watchfiles --filter python 'celery -A celery_broker.main.celery_app worker -l info -P solo -n upload_worker -Q upload_queue'

  flower:
    container_name: flower
    image: mher/flower
    command: celery flower -p 5555
    env_file: .env
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - web_api

  minio:
    container_name: minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio:/data
    env_file: .env
    command: server --console-address ":9090" /data

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db


volumes:
  minio:
  tmp:
  mongodb: