services:
  minio:
    image: minio/minio
    ports:
      - "9000:9010"
      - "9001:9001"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
    command: server --console-address ":9001" /data

volumes:
  minio: