name: Testing deployment

on:
  push:

jobs:
  unit-test:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name : Install Packages 
        run : pip install -r requirements.txt

      - name: test
        run: python -m unittest